RentCycleWebAppFinal/RentCycleWebApp/Controllers/DeviceModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RentCycleWebApp.Data;
using RentCycleWebApp.Models;

namespace RentCycleWebApp.Controllers
{
    public class DeviceModelsController : Controller
    {
        private readonly RentCycleWebAppDBContext _context;

        public DeviceModelsController(RentCycleWebAppDBContext context)
        {
            _context = context;
        }

        // GET: DeviceModels
        public async Task<IActionResult> Index()
        {
              return View(await _context.DeviceModels.ToListAsync());
        }

        // GET: DeviceModels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.DeviceModels == null)
            {
                return NotFound();
            }

            var deviceModel = await _context.DeviceModels
                .FirstOrDefaultAsync(m => m.Id == id);
            if (deviceModel == null)
            {
                return NotFound();
            }

            return View(deviceModel);
        }

        // GET: DeviceModels/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: DeviceModels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,DeviceModel1")] DeviceModel deviceModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(deviceModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(deviceModel);
        }

        // GET: DeviceModels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.DeviceModels == null)
            {
                return NotFound();
            }

            var deviceModel = await _context.DeviceModels.FindAsync(id);
            if (deviceModel == null)
            {
                return NotFound();
            }
            return View(deviceModel);
        }

        // POST: DeviceModels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,DeviceModel1")] DeviceModel deviceModel)
        {
            if (id != deviceModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(deviceModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DeviceModelExists(deviceModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(deviceModel);
        }

        // GET: DeviceModels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.DeviceModels == null)
            {
                return NotFound();
            }

            var deviceModel = await _context.DeviceModels
                .FirstOrDefaultAsync(m => m.Id == id);
            if (deviceModel == null)
            {
                return NotFound();
            }

            return View(deviceModel);
        }

        // POST: DeviceModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.DeviceModels == null)
            {
                return Problem("Entity set 'RentCycleWebAppDBContext.DeviceModels'  is null.");
            }
            var deviceModel = await _context.DeviceModels.FindAsync(id);
            if (deviceModel != null)
            {
                _context.DeviceModels.Remove(deviceModel);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DeviceModelExists(int id)
        {
          return _context.DeviceModels.Any(e => e.Id == id);
        }
    }
}

RentCycleWebAppFinal/RentCycleWebApp/Controllers/DeviceRatesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RentCycleWebApp.Data;
using RentCycleWebApp.Models;

namespace RentCycleWebApp.Controllers
{
    public class DeviceRatesController : Controller
    {
        private readonly RentCycleWebAppDBContext _context;

        public DeviceRatesController(RentCycleWebAppDBContext context)
        {
            _context = context;
        }

        // GET: DeviceRates
        public async Task<IActionResult> Index()
        {
            var rentCycleWebAppDBContext = _context.DeviceRates.Include(d => d.DeviceModel).Include(d => d.UserCategory);
            return View(await rentCycleWebAppDBContext.ToListAsync());
        }

        // GET: DeviceRates/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.DeviceRates == null)
            {
                return NotFound();
            }

            var deviceRate = await _context.DeviceRates
                .Include(d => d.DeviceModel)
                .Include(d => d.UserCategory)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (deviceRate == null)
            {
                return NotFound();
            }

            return View(deviceRate);
        }

        // GET: DeviceRates/Create
        public IActionResult Create()
        {
            ViewData["DeviceModelId"] = new SelectList(_context.DeviceModels, "Id", "DeviceModel1");
            ViewData["UserCategoryId"] = new SelectList(_context.UserCategories, "Id", "UserCategory1");
            return View();
        }

        // POST: DeviceRates/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,DeviceModelId,UserCategoryId,Rate,StartTime,EndTime,EffectiveStartDate,EffectiveEndDate")] DeviceRate deviceRate)
        {
            if (ModelState.IsValid)
            {
                _context.Add(deviceRate);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["DeviceModelId"] = new SelectList(_context.DeviceModels, "Id", "DeviceModel1", deviceRate.DeviceModelId);
            ViewData["UserCategoryId"] = new SelectList(_context.UserCategories, "Id", "UserCategory1", deviceRate.UserCategoryId);
            return View(deviceRate);
        }

        // GET: DeviceRates/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.DeviceRates == null)
            {
                return NotFound();
            }

            var deviceRate = await _context.DeviceRates.FindAsync(id);
            if (deviceRate == null)
            {
                return NotFound();
            }
            ViewData["DeviceModelId"] = new SelectList(_context.DeviceModels, "Id", "DeviceModel1", deviceRate.DeviceModelId);
            ViewData["UserCategoryId"] = new SelectList(_context.UserCategories, "Id", "UserCategory1", deviceRate.UserCategoryId);
            return View(deviceRate);
        }

        // POST: DeviceRates/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,DeviceModelId,UserCategoryId,Rate,StartTime,EndTime,EffectiveStartDate,EffectiveEndDate")] DeviceRate deviceRate)
        {
            if (id != deviceRate.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(deviceRate);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DeviceRateExists(deviceRate.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DeviceModelId"] = new SelectList(_context.DeviceModels, "Id", "DeviceModel1", deviceRate.DeviceModelId);
            ViewData["UserCategoryId"] = new SelectList(_context.UserCategories, "Id", "UserCategory1", deviceRate.UserCategoryId);
            return View(deviceRate);
        }

        // GET: DeviceRates/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.DeviceRates == null)
            {
                return NotFound();
            }

            var deviceRate = await _context.DeviceRates
                .Include(d => d.DeviceModel)
                .Include(d => d.UserCategory)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (deviceRate == null)
            {
                return NotFound();
            }

            return View(deviceRate);
        }

        // POST: DeviceRates/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.DeviceRates == null)
            {
                return Problem("Entity set 'RentCycleWebAppDBContext.DeviceRates'  is null.");
            }
            var deviceRate = await _context.DeviceRates.FindAsync(id);
            if (deviceRate != null)
            {
                _context.DeviceRates.Remove(deviceRate);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DeviceRateExists(int id)
        {
          return _context.DeviceRates.Any(e => e.Id == id);
        }
    }
}

RentCycleWebAppFinal/RentCycleWebApp/Controllers/PaymentModesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RentCycleWebApp.Data;
using RentCycleWebApp.Models;

namespace RentCycleWebApp.Controllers
{
    public class PaymentModesController : Controller
    {
        private readonly RentCycleWebAppDBContext _context;

        public PaymentModesController(RentCycleWebAppDBContext context)
        {
            _context = context;
        }

        // GET: PaymentModes
        public async Task<IActionResult> Index()
        {
              return View(await _context.PaymentModes.ToListAsync());
        }

        // GET: PaymentModes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.PaymentModes == null)
            {
                return NotFound();
            }

            var paymentMode = await _context.PaymentModes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (paymentMode == null)
            {
                return NotFound();
            }

            return View(paymentMode);
        }

        // GET: PaymentModes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: PaymentModes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,PaymentMode1")] PaymentMode paymentMode)
        {
            if (ModelState.IsValid)
            {
                _context.Add(paymentMode);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(paymentMode);
        }

        // GET: PaymentModes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.PaymentModes == null)
            {
                return NotFound();
            }

            var paymentMode = await _context.PaymentModes.FindAsync(id);
            if (paymentMode == null)
            {
                return NotFound();
            }
            return View(paymentMode);
        }

        // POST: PaymentModes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,PaymentMode1")] PaymentMode paymentMode)
        {
            if (id != paymentMode.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(paymentMode);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PaymentModeExists(paymentMode.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(paymentMode);
        }

        // GET: PaymentModes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.PaymentModes == null)
            {
                return NotFound();
            }

            var paymentMode = await _context.PaymentModes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (paymentMode == null)
            {
                return NotFound();
            }

            return View(paymentMode);
        }

        // POST: PaymentModes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.PaymentModes == null)
            {
                return Problem("Entity set 'RentCycleWebAppDBContext.PaymentModes'  is null.");
            }
            var paymentMode = await _context.PaymentModes.FindAsync(id);
            if (paymentMode != null)
            {
                _context.PaymentModes.Remove(paymentMode);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PaymentModeExists(int id)
        {
          return _context.PaymentModes.Any(e => e.Id == id);
        }
    }
}

RentCycleWebAppFinal/RentCycleWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RentCycleWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RentCycleWebApp.styles.css" asp-append-version="true" />

    <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">-->
    

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/cyclelogo.png"
                                         style="width: 85px;" alt="logo"></a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                       <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item dropdown">
                          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Master Data
                          </a>
                          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="nav-link text-dark" asp-area="" asp-controller="DeviceModels" asp-action="Index">Device Models</a></li>
                            <li><a class="nav-link text-dark" asp-area="" asp-controller="DeviceRates" asp-action="Index">Device Rates</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="nav-link text-dark" asp-area="" asp-controller="PaymentModes" asp-action="Index">Payment Modes</a></li>
                             <li><hr class="dropdown-divider"></li>
                             <li><a class="nav-link text-dark" asp-area="" asp-controller="UserCategories" asp-action="Index">User Categories</a></li>
                          </ul>
                        </li>

                        <li class="nav-item dropdown">
                          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Device Data
                          </a>
                          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="nav-link text-dark" asp-area="" asp-controller="DeviceShadows" asp-action="Index">Device Shadows</a></li>
                           </ul>
                        </li>
                        <li class="nav-item dropdown">
                          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            User Data
                          </a>
                          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="nav-link text-dark" asp-area="" asp-controller="UserAccounts" asp-action="Index">User Accounts</a></li>
                             <li><a class="nav-link text-dark" asp-area="" asp-controller="UserAccountBalances" asp-action="Index">User Account Balances</a></li>
                              <li> <a class="nav-link text-dark" asp-area="" asp-controller="UserPayments" asp-action="Index">User Payments</a></li>
                               <li> <a class="nav-link text-dark" asp-area="" asp-controller="UserRideCosts" asp-action="Index">User Ride Costs</a></li>
                                <li><a class="nav-link text-dark" asp-area="" asp-controller="UserRideInfoes" asp-action="Index">User Ride Infoes</a></li>
                           </ul>
                        </li>
                       
                       
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Rent Cycle - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

   <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
     <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>-->


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

RentCycleWebAppFinal/RentCycleWebApp/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RentCycleWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RentCycleWebApp.styles.css" asp-append-version="true" />
</head>
<body>
   
    <div class="container-fluid">
            @RenderBody()
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - RentCycleWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>